// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU05uYQXTX0x_xwpcQRbb5YGlYBmqprBc',
    appId: '1:1084624462571:web:5349c80dcb7558e55394ae',
    messagingSenderId: '1084624462571',
    projectId: 'couponat-e3984',
    authDomain: 'couponat-e3984.firebaseapp.com',
    storageBucket: 'couponat-e3984.appspot.com',
    measurementId: 'G-92LGDZFHYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD63HSrOg94nYf7WRh2y7MEaRUcqMOQXvk',
    appId: '1:1084624462571:android:cd316c9734e938115394ae',
    messagingSenderId: '1084624462571',
    projectId: 'couponat-e3984',
    storageBucket: 'couponat-e3984.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOCoa4IEq4Z5Zvegjv8FrR9PoU3_b8DWk',
    appId: '1:1084624462571:ios:693e25916c32d4c85394ae',
    messagingSenderId: '1084624462571',
    projectId: 'couponat-e3984',
    storageBucket: 'couponat-e3984.appspot.com',
    iosBundleId: 'com.example.couponat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOCoa4IEq4Z5Zvegjv8FrR9PoU3_b8DWk',
    appId: '1:1084624462571:ios:3d021e7a934716c65394ae',
    messagingSenderId: '1084624462571',
    projectId: 'couponat-e3984',
    storageBucket: 'couponat-e3984.appspot.com',
    iosBundleId: 'com.example.couponat.RunnerTests',
  );
}
